describe("core/log.lua", function()
    local Ledger

    before_each(function()
        Ledger = {}
        local chunk = assert(loadfile("Ledger/core/log.lua"))
        chunk("Ledger", Ledger)
    end)

    it("starts at trace, with chat echo disabled and an empty buffer", function()
        local state = Ledger.NewLogState()
        assert.are.equal("trace", state.level)
        assert.is_false(state.chat)
        assert.are.same({}, state.buffer)
    end)

    describe("SetLogLevel", function()
        it("accepts a valid level", function()
            local state = Ledger.NewLogState()
            assert.is_true(Ledger.SetLogLevel(state, "trace"))
            assert.are.equal("trace", state.level)
        end)

        it("rejects an invalid level without touching the state", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "error")
            assert.is_false(Ledger.SetLogLevel(state, "bogus"))
            assert.are.equal("error", state.level)
        end)
    end)

    describe("LogMessage: filtering by level", function()
        it("with level off records nothing", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "off")
            Ledger.LogMessage(state, "error", "algo", 0)
            assert.are.same({}, state.buffer)
        end)

        it("with level info records error and info but not trace", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "info")
            Ledger.LogMessage(state, "error", "e", 0)
            Ledger.LogMessage(state, "info", "i", 0)
            Ledger.LogMessage(state, "trace", "t", 0)

            assert.are.equal(2, #state.buffer)
            assert.are.equal("error", state.buffer[1].level)
            assert.are.equal("info", state.buffer[2].level)
        end)

        it("with level trace records all three", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            Ledger.LogMessage(state, "error", "e", 0)
            Ledger.LogMessage(state, "info", "i", 0)
            Ledger.LogMessage(state, "trace", "t", 0)

            assert.are.equal(3, #state.buffer)
        end)

        it("ignores an invalid message level", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            local echo = Ledger.LogMessage(state, "bogus", "x", 0)

            assert.is_false(echo)
            assert.are.same({}, state.buffer)
        end)
    end)

    describe("LogMessage: chat echo", function()
        it("returns false if chat echo is disabled", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            assert.is_false(Ledger.LogMessage(state, "info", "i", 0))
        end)

        it("returns true if echo is enabled and the message passed the filter", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            Ledger.SetLogChat(state, true)
            assert.is_true(Ledger.LogMessage(state, "info", "i", 0))
        end)

        it("doesn't echo a message the level filter blocks", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "error")
            Ledger.SetLogChat(state, true)
            assert.is_false(Ledger.LogMessage(state, "trace", "t", 0))
        end)
    end)

    describe("ToggleLogChat", function()
        it("toggles the flag and returns the new value", function()
            local state = Ledger.NewLogState()
            assert.is_true(Ledger.ToggleLogChat(state))
            assert.is_false(Ledger.ToggleLogChat(state))
        end)
    end)

    describe("ring buffer", function()
        it("discards the oldest entries once capacity is exceeded", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            for i = 1, Ledger.LOG_BUFFER_CAPACITY + 10 do
                Ledger.LogMessage(state, "trace", "msg" .. i, i)
            end

            assert.are.equal(Ledger.LOG_BUFFER_CAPACITY, #state.buffer)
            assert.are.equal("msg11", state.buffer[1].msg)
            assert.are.equal("msg" .. (Ledger.LOG_BUFFER_CAPACITY + 10), state.buffer[#state.buffer].msg)
        end)
    end)

    describe("FormatLogBuffer", function()
        it("indicates when the buffer is empty", function()
            local state = Ledger.NewLogState()
            assert.are.equal("(log buffer empty)", Ledger.FormatLogBuffer(state))
        end)

        it("formats each entry with its level and message, oldest first", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "info")
            Ledger.LogMessage(state, "error", "first", 0)
            Ledger.LogMessage(state, "info", "second", 1)

            assert.are.equal("[error] first\n[info] second", Ledger.FormatLogBuffer(state))
        end)
    end)
end)
