describe("core/log.lua", function()
    local Ledger

    before_each(function()
        Ledger = {}
        local chunk = assert(loadfile("Ledger/core/log.lua"))
        chunk("Ledger", Ledger)
    end)

    it("empieza en off, sin eco a chat y con el buffer vacio", function()
        local state = Ledger.NewLogState()
        assert.are.equal("off", state.level)
        assert.is_false(state.chat)
        assert.are.same({}, state.buffer)
    end)

    describe("SetLogLevel", function()
        it("acepta un nivel valido", function()
            local state = Ledger.NewLogState()
            assert.is_true(Ledger.SetLogLevel(state, "trace"))
            assert.are.equal("trace", state.level)
        end)

        it("rechaza un nivel invalido sin tocar el estado", function()
            local state = Ledger.NewLogState()
            assert.is_false(Ledger.SetLogLevel(state, "bogus"))
            assert.are.equal("off", state.level)
        end)
    end)

    describe("LogMessage: filtrado por nivel", function()
        it("con nivel off no registra nada", function()
            local state = Ledger.NewLogState()
            Ledger.LogMessage(state, "error", "algo", 0)
            assert.are.same({}, state.buffer)
        end)

        it("con nivel info registra error e info pero no trace", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "info")
            Ledger.LogMessage(state, "error", "e", 0)
            Ledger.LogMessage(state, "info", "i", 0)
            Ledger.LogMessage(state, "trace", "t", 0)

            assert.are.equal(2, #state.buffer)
            assert.are.equal("error", state.buffer[1].level)
            assert.are.equal("info", state.buffer[2].level)
        end)

        it("con nivel trace registra los tres", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            Ledger.LogMessage(state, "error", "e", 0)
            Ledger.LogMessage(state, "info", "i", 0)
            Ledger.LogMessage(state, "trace", "t", 0)

            assert.are.equal(3, #state.buffer)
        end)

        it("ignora un nivel de mensaje invalido", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            local echo = Ledger.LogMessage(state, "bogus", "x", 0)

            assert.is_false(echo)
            assert.are.same({}, state.buffer)
        end)
    end)

    describe("LogMessage: eco a chat", function()
        it("devuelve false si el eco a chat esta desactivado", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            assert.is_false(Ledger.LogMessage(state, "info", "i", 0))
        end)

        it("devuelve true si el eco esta activado y el mensaje paso el filtro", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            Ledger.SetLogChat(state, true)
            assert.is_true(Ledger.LogMessage(state, "info", "i", 0))
        end)

        it("no ecoa un mensaje que el filtro de nivel bloquea", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "error")
            Ledger.SetLogChat(state, true)
            assert.is_false(Ledger.LogMessage(state, "trace", "t", 0))
        end)
    end)

    describe("ToggleLogChat", function()
        it("alterna el flag y devuelve el nuevo valor", function()
            local state = Ledger.NewLogState()
            assert.is_true(Ledger.ToggleLogChat(state))
            assert.is_false(Ledger.ToggleLogChat(state))
        end)
    end)

    describe("buffer en anillo", function()
        it("descarta las entradas mas antiguas al superar la capacidad", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "trace")
            for i = 1, Ledger.LOG_BUFFER_CAPACITY + 10 do
                Ledger.LogMessage(state, "trace", "msg" .. i, i)
            end

            assert.are.equal(Ledger.LOG_BUFFER_CAPACITY, #state.buffer)
            assert.are.equal("msg11", state.buffer[1].msg)
            assert.are.equal("msg" .. (Ledger.LOG_BUFFER_CAPACITY + 10), state.buffer[#state.buffer].msg)
        end)
    end)

    describe("FormatLogBuffer", function()
        it("indica cuando el buffer esta vacio", function()
            local state = Ledger.NewLogState()
            assert.are.equal("(buffer de log vacio)", Ledger.FormatLogBuffer(state))
        end)

        it("formatea cada entrada con su nivel y mensaje, mas antigua primero", function()
            local state = Ledger.NewLogState()
            Ledger.SetLogLevel(state, "info")
            Ledger.LogMessage(state, "error", "primero", 0)
            Ledger.LogMessage(state, "info", "segundo", 1)

            assert.are.equal("[error] primero\n[info] segundo", Ledger.FormatLogBuffer(state))
        end)
    end)
end)
