describe("core/slash_command.lua", function()
    local Ledger

    before_each(function()
        Ledger = {}
        local chunk = assert(loadfile("Ledger/core/slash_command.lua"))
        chunk("Ledger", Ledger)
    end)

    describe("empty command", function()
        it("returns an empty subcommand with no arguments for an empty string", function()
            local command, args = Ledger.ParseCommand("")
            assert.are.equal("", command)
            assert.are.same({}, args)
        end)

        it("treats nil the same as an empty string", function()
            local command, args = Ledger.ParseCommand(nil)
            assert.are.equal("", command)
            assert.are.same({}, args)
        end)

        it("the empty command is a known subcommand", function()
            assert.is_true(Ledger.IsKnownCommand(""))
        end)
    end)

    describe("standalone subcommand", function()
        it("recognizes a subcommand with no arguments", function()
            local command, args = Ledger.ParseCommand("reset")
            assert.are.equal("reset", command)
            assert.are.same({}, args)
            assert.is_true(Ledger.IsKnownCommand(command))
        end)
    end)

    describe("subcommand with an argument", function()
        it("splits the subcommand from its argument", function()
            local command, args = Ledger.ParseCommand("log info")
            assert.are.equal("log", command)
            assert.are.same({ "info" }, args)
        end)
    end)

    describe("unknown argument", function()
        it("parses it the same, without validating it: validation is the dispatcher's job", function()
            local command, args = Ledger.ParseCommand("log foo")
            assert.are.equal("log", command)
            assert.are.same({ "foo" }, args)
        end)

        it("an unknown top-level subcommand doesn't show up as known", function()
            local command = Ledger.ParseCommand("bogus")
            assert.are.equal("bogus", command)
            assert.is_false(Ledger.IsKnownCommand(command))
        end)
    end)

    describe("extra whitespace", function()
        it("ignores extra whitespace at the start, middle and end", function()
            local command, args = Ledger.ParseCommand("   log    info   ")
            assert.are.equal("log", command)
            assert.are.same({ "info" }, args)
        end)
    end)

    describe("uppercase", function()
        it("normalizes the subcommand and arguments to lowercase", function()
            local command, args = Ledger.ParseCommand("LOG Info")
            assert.are.equal("log", command)
            assert.are.same({ "info" }, args)
        end)
    end)

    describe("HelpText", function()
        it("includes one line per declared subcommand", function()
            local text = Ledger.HelpText()
            for _, cmd in ipairs(Ledger.SLASH_COMMANDS) do
                assert.is_not_nil(text:find(cmd.desc, 1, true))
            end
        end)
    end)
end)
